Feat/animations
arthurfaby/HumanGL pull request #11
Opened 2024-12-13 14:36 UTC by arthurfaby

2024-12-15 15:19 UTC, SirGabriele requested changes

2024-12-15 15:19 UTC, SirGabriele commented on src/animations/Animation.cpp
> +        return;
```suggestion
    if (_keyframes.empty())
    {
        return;
    }
```

2024-12-15 15:19 UTC, SirGabriele commented on src/animations/Animation.cpp
> +                prevKeyframe = &_keyframes[i - 1];
```suggestion
            if (i > 0)
            {
                prevKeyframe = &_keyframes[i - 1];
            }
```

2024-12-15 15:19 UTC, SirGabriele commented on src/camera/Camera.cpp
> +    getInstance()._yaw = -90.0f;
Si on réutilise ces valeurs il faudrait les garder en mémoire leur valeur de base, fais y moi penser et je le ferai lundi

2024-12-15 15:19 UTC, SirGabriele commented on include/camera/Camera.hpp
> +    static void deleteCamera();
Rien à faire dans les getters

2024-12-15 15:19 UTC, SirGabriele commented on src/body-parts/BodyPart.cpp
> +    _translationMatrix = Matrix4::createTranslationMatrix(_translateX, y, _translateZ);
- Ça ne va pas écraser la translationMatrix de faire un `=`? On ne veut ajouter, et donc faire un `translationMatrix *= Matrix4::create...`?
- Est-ce que tu as vraiment besoin de séparer toutes les transformations en X, Y et Z? `setTranslateY` qui appelle `Matrix4::createTranslationMatrix(_translateX, y, _translateZ)` c'est pas foufou. Cette réflexion est valide pour toutes les propriétés que tu as séparées en X, Y et Z

2024-12-15 15:19 UTC, SirGabriele commented on src/body-parts/BodyPart.cpp
> +    _translationMatrix = Matrix4::createTranslationMatrix(_translateX, _translateY, z);
Même question qu'au dessus

2024-12-15 15:19 UTC, SirGabriele commented on src/animations/Animation.cpp
> +        return;
```suggestion
    if (_keyframes.empty()) return;
```

2024-12-15 15:19 UTC, SirGabriele commented on src/animations/Animation.cpp
> +        return;
Au choix

2024-12-15 15:19 UTC, SirGabriele commented on include/body-parts/Human.hpp
> +    [[nodiscard]] BodyPart* getRoot() const;
Quid de la `targetBodyPart`? J'en ai besoin pour le mouse picking

2024-12-15 15:19 UTC, SirGabriele commented on src/main.cpp
> +        selectedHuman->getRoot()->rotateX(ROTATION_SPEED);
Ici il faudra changer par `getTargetBodyPart`

2024-12-15 15:19 UTC, SirGabriele commented on src/main.cpp
> +void generateStayingPutKeyframes(Human* human)
Je te propose de déplacer toutes ces méthodes liées aux keyframes dans un fichier à part pour alléger le main. On pourrait également faire ça pour les raccourcis

2024-12-15 15:19 UTC, SirGabriele commented on src/main.cpp
> +    // Camera::deleteCamera();
Pourquoi deleteCamera est en commentaire?

2024-12-15 15:19 UTC, SirGabriele commented on src/shaders/fragmentShader.glsl
> +}
- Los tabos por favor
- En vrai on peut remettre `finalColor = fragmentColor`. Inutile de recréer un vec3 pour ça, maintenant je suis plus à l'aise avec les vecteurs donc j'ai plus besoin de clarifier le .r.g.b

2024-12-15 15:19 UTC, SirGabriele commented on src/shaders/vertexShader.glsl
> +uniform mat4 projection;// Projection matrix
Ah c'est intentionnel d'enlever les tabs? Porque D:

2024-12-16 07:31 UTC, arthurfaby commented on CMakeLists.txt
> +        src/animations/Animation.cpp
Fait

2024-12-16 07:40 UTC, arthurfaby commented on include/animations/Animation.hpp
> +};
Fait

2024-12-16 07:40 UTC, arthurfaby commented on src/animations/Animation.cpp
> +        return;
Fait

2024-12-16 07:58 UTC, arthurfaby commented on src/main.cpp
> +    // Camera::deleteCamera();
Remis

2024-12-16 08:03 UTC, arthurfaby commented on include/camera/Camera.hpp
> +    static void deleteCamera();
Fait

2024-12-16 08:11 UTC, arthurfaby commented on src/main.cpp
> +void generateStayingPutKeyframes(Human* human)
Fait

2024-12-16 08:12 UTC, arthurfaby commented on src/main.cpp
> +    // Camera::deleteCamera();
Aucune idée, c'est fox

2024-12-16 08:15 UTC, arthurfaby commented on src/shaders/vertexShader.glsl
> +uniform mat4 projection;// Projection matrix
Formatter...

2024-12-16 08:15 UTC, arthurfaby commented on src/shaders/fragmentShader.glsl
> +}
Fait

2024-12-16 08:15 UTC, arthurfaby commented on include/body-parts/Human.hpp
> +    [[nodiscard]] BodyPart* getRoot() const;
C'est toi que le feras pendant le merge

2024-12-16 08:27 UTC, SirGabriele approved these changes

2024-12-16 08:27 UTC, merged